### ISSUE TITLE
Live list

### ISSUE THREAD

**Issue by EKhots** [tailsjs/likee-api-wrapper#1]
Greetings.

**Comment by tailsjs** [comment]
Yep, but it's need to do some reverse engineering of likee mobile app.

**Comment by Nebrassk** [comment]
Hi bro
Please my friend I need to contact you
I am a recharge agent in Likee and I found out how to ship via API, but the problem is the end of the token and I do not know how to generate a new token
Does it come from the application or from a VPN and is added with headers?

telegram t.me/carddoom

**Comment by tailsjs** [comment]
Hi, @Nebrassk 
I guess it generates in application. But idk, i still didn't reversed Likee application (because i still didn't rooted my phone :(. Maybe when I get around to rooting my phone, I'll look into it then.)
